version: '3'

services:
  backend:
    image: macevedg/spring-protobuf-server
    ports: 
    - "8080:8080"

  frontend:
    image: macevedg/protobuf-frontend
    ports: 
    - "80:80"
    depends_on: 
    - backend
